#!/usr/bin/env bash
echo "Time started  :  "$(date)
echo "Retrieve metadata via Google Docs..."
utils/refresh
echo "Extract ISSNs..."
utils/parse
echo "Retrieve ISSN-Ls and all related ISSNs..."
utils/enrich_cieps
echo "Extract all ISSNs..."
utils/parse2
echo "Enrich via OpenAlex..."
utils/enrich_openalex
echo "Time finished :  "$(date)
