#!/usr/bin/env Rscript
fps <- list.files(
  "docs",
  pattern = ".*\\.Rmd",
  full.names = TRUE,
  recursive = TRUE
)
for (fp in fps) {
  rmarkdown::render(fp, output_format = "all", output_dir = "public")
}
