---
title: "DOAJ Changelog"
subtitle: "Withdrawn Journals"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
lang: "en-US"
output:
  html_document:
    #toc: true
    #toc_depth: 2
    mathjax: null
    keep_md: false
    df_print: paged
    css: ["assets/css/custom.css"]
    includes:
      after_body: assets/html/target.html
---
```{r setup, include=F}
# nolint start: line_length_linter, commented_code_linter.
knitr::opts_chunk$set(
  echo = FALSE,
  error = FALSE,
  message = FALSE,
  warning = FALSE
)
knitr::opts_knit$set(
  root.dir = ".."
)
```

```{r source-remote, eval=F}
doaj_journals <- readr::read_csv("https://doaj.org/csv", show_col_types = FALSE)
```

```{r source-local}
doaj_journals_withdrawn <- readr::read_csv("data/doaj_changelog_withdrawn_list_enriched_utf8.csv", show_col_types = FALSE)
```

```{r doaj-publisher-mapping, eval=F}
# Mapping by @MiWohlgemuth
doaj_journals[grepl("Elsevier|KeAi Communications", doaj_journals$Publisher, ignore.case = TRUE), "Publisher"] <- "Elsevier"
doaj_journals[grepl("Wiley|American Geophysical Union", doaj_journals$Publisher, ignore.case = TRUE), "Publisher"] <- "Wiley"
doaj_journals[grepl("BMC|Springer|Nature Publishing|Nature Portfolio", doaj_journals$Publisher, ignore.case = TRUE), "Publisher"] <- "Springer Nature"
doaj_journals[grepl("Taylor & Francis|F1000 Research|Dove Medical", doaj_journals$Publisher, ignore.case = TRUE), "Publisher"] <- "Taylor & Francis"
doaj_journals[grepl("Wolters Kluwer", doaj_journals$Publisher, ignore.case = TRUE), "Publisher"] <- "Wolters Kluwer"
doaj_journals[grepl("SAGE|Sage Publishing|Mary Ann Liebert", doaj_journals$Publisher, ignore.case = FALSE), "Publisher"] <- "SAGE"
doaj_journals[grepl("De Gruyter|Brill|Vandenhoeck|Sciendo", doaj_journals$Publisher, ignore.case = FALSE), "Publisher"] <- "De Gruyter Brill"
doaj_journals[grepl("MDPI", doaj_journals$Publisher, ignore.case = FALSE), "Publisher"] <- "MDPI"
doaj_journals[grepl("Frontiers Media", doaj_journals$Publisher, ignore.case = FALSE), "Publisher"] <- "Frontiers"
```

DOI: [10.5281/zenodo.15866633](https://doi.org/10.5281/zenodo.15866633)

# Plots

```{r doaj-withdrawn-plots-df}
doaj_journals_withdrawn_plots <- doaj_journals_withdrawn[, c("title", "reason", "date_removed")]
doaj_journals_withdrawn_plots$date_removed_year <- format(doaj_journals_withdrawn_plots$date_removed, "%Y")
```

```{r doaj-withdrawn-plots-count-per-year}
ggplot2::ggplot(doaj_journals_withdrawn_plots, ggplot2::aes(x = date_removed_year)) + ggplot2::geom_bar() +
  ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 0, vjust = 0.5, hjust = 1)) +
  ggplot2::xlab("Year Withdrawn")  + ggplot2::ylab("Number of journals") + ggplot2::labs(title = "Journals withdrawn from DOAJ per Year")
```

```{r doaj-withdrawn-plots-count-per-year-and-reason}
ggplot2::ggplot(doaj_journals_withdrawn_plots, ggplot2::aes(x = date_removed_year)) + ggplot2::geom_bar() + ggplot2::facet_grid(reason ~ .) +
  ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 0, vjust = 0.5, hjust = 1)) +
  ggplot2::xlab("Year Withdrawn")  + ggplot2::ylab("Number of journals") + ggplot2::labs(title = "Journals withdrawn from DOAJ per Reason and Year")
```

```{r doaj-withdrawn-plots-not-best-df}
doaj_journals_withdrawn_select <- grepl("Journal not adhering to Best practice", doaj_journals_withdrawn$reason) & doaj_journals_withdrawn$publisher %in% c("SpringerNature", "Wiley", "Elsevier", "SAGE", "MDPI", "Oxford University Press", "De Gruyter Brill", "Taylor & Francis", "Wolters Kluwer", "Frontiers")
doaj_journals_withdrawn_plots2 <- doaj_journals_withdrawn[doaj_journals_withdrawn_select, c("title", "issn_l", "date_removed", "reason", "publisher")]
doaj_journals_withdrawn_plots2$date_removed_year <- format(doaj_journals_withdrawn_plots2$date_removed, "%Y")
doaj_journals_withdrawn_plots2 <- dplyr::count(doaj_journals_withdrawn_plots2, publisher, date_removed_year)
```

```{r doaj-withdrawn-plots-not-best-count-per-publisher-and-year}
ggplot2::ggplot(doaj_journals_withdrawn_plots2, ggplot2::aes(x = date_removed_year, y = n)) + ggplot2::geom_col() + ggplot2::facet_grid(publisher ~ .) +
  ggplot2::geom_text(ggplot2::aes(x = date_removed_year, y = n, label = n), size = 2, vjust = -0.3, colour = "gray40") +
  ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 0, vjust = 0.5, hjust = 1)) +
  ggplot2::xlab("Year Withdrawn")  + ggplot2::ylab("Number of journals") + ggplot2::labs(title = "Journals withdrawn from DOAJ per Publisher and Year")
```

<!-- 
# Top 100 Publishers of Withdrawn Journals
-->

```{r doaj-publishers-withdrawn, eval=F}
doaj_publishers_withdrawn <- setNames(
  as.data.frame(
    table(doaj_journals_withdrawn$publisher), stringsAsFactors = FALSE
  )[order(table(doaj_journals_withdrawn$publisher), decreasing = TRUE), ],
  c("Publisher", "Journal Count")
)
```

```{r doaj-publishers-withdrawn-display, rownames.print=F, eval=F}
doaj_publishers_withdrawn[1:100, ]
```

<!--
# Top 100 Publishers of Indexed Journals
-->

```{r doaj-publishers-indexed, eval=F}
doaj_publishers <- setNames(
  as.data.frame(
    table(doaj_journals$Publisher), stringsAsFactors = FALSE
  )[order(table(doaj_journals$Publisher), decreasing = TRUE), ],
  c("Publisher", "Journal Count")
)
```

```{r doaj-publishers-indexed-display, rownames.print=F, eval=F}
doaj_publishers[1:100, ]
```

---

```{r linter-halt}
# nolint end
```
